/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    categories: Category;
    tags: Tag;
    videos: Video;
    'magazine-issues': MagazineIssue;
    pages: Page;
    ads: Ad;
    redirects: Redirect;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'magazine-issues': MagazineIssuesSelect<false> | MagazineIssuesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    ads: AdsSelect<false> | AdsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'main-menu': MainMenu;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'main-menu': MainMenuSelect<false> | MainMenuSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * ملخص قصير يظهر في البطاقات ونتائج البحث.
   */
  excerpt?: string | null;
  /**
   * اختر صورة أو رابط فيديو ليظهر في رأس المقال.
   */
  featuredType?: ('image' | 'video') | null;
  /**
   * تُستخدم كغلاف على البطاقات، وكصورة مصغّرة للفيديو.
   */
  featuredImage?: (number | null) | Media;
  /**
   * رابط YouTube/Vimeo (يُحمَّل الإطار عند النقر فقط). المصادر غير المدعومة تُعرض كرابط خارجي.
   */
  featuredVideoUrl?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isRecipe?: boolean | null;
  recipe?: {
    /**
     * مثال: 20 دقيقة
     */
    prepTime?: string | null;
    cookTime?: string | null;
    servings?: string | null;
    /**
     * مثال: مغربي
     */
    cuisine?: string | null;
    ingredients?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    instructions?:
      | {
          step: string;
          id?: string | null;
        }[]
      | null;
  };
  category: number | Category;
  tags?: (number | Tag)[] | null;
  authors?: (number | User)[] | null;
  publishedAt?: string | null;
  /**
   * يُولّد تلقائيًا من العنوان. الرابط الدائم يعتمد على المعرّف الرقمي، فيمكن تعديله بأمان.
   */
  slug?: string | null;
  /**
   * اتركها فارغة لاستخدام العنوان والمقتطف والصورة البارزة افتراضيًا.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  legacyWpId?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * وصف موجز للصورة لأغراض الوصول وتحسين محركات البحث (إلزامي).
   */
  alt: string;
  caption?: string | null;
  /**
   * مصدر الصورة أو صاحب الحقوق (مهم لصور المشاهير).
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  parent?: (number | null) | Category;
  description?: string | null;
  /**
   * يُولّد تلقائيًا من العنوان. الرابط الدائم يعتمد على المعرّف الرقمي، فيمكن تعديله بأمان.
   */
  slug?: string | null;
  /**
   * اتركها فارغة لاستخدام العنوان والمقتطف والصورة البارزة افتراضيًا.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * يُولّد تلقائيًا من العنوان. الرابط الدائم يعتمد على المعرّف الرقمي، فيمكن تعديله بأمان.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'journalist';
  bio?: string | null;
  avatar?: (number | null) | Media;
  title?: string | null;
  social?: {
    facebook?: string | null;
    x?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * مجموعة الفيديو المستقلة متقاعدة — الفيديو الآن خاصية للمقال.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  /**
   * يُحمَّل الإطار فقط عند النقر (نمط الواجهة المؤجلة) لأداء أفضل.
   */
  videoUrl: string;
  thumbnail?: (number | null) | Media;
  description?: string | null;
  /**
   * مثال: 04:32 (تُستخدم في بيانات VideoObject).
   */
  duration?: string | null;
  category?: (number | null) | Category;
  publishedAt?: string | null;
  /**
   * يُولّد تلقائيًا من العنوان. الرابط الدائم يعتمد على المعرّف الرقمي، فيمكن تعديله بأمان.
   */
  slug?: string | null;
  /**
   * اتركها فارغة لاستخدام العنوان والمقتطف والصورة البارزة افتراضيًا.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * الأعداد الرقمية المرقّمة من مجلة لالة فاطمة (غلاف + PDF).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazine-issues".
 */
export interface MagazineIssue {
  id: number;
  issueNumber: number;
  /**
   * مثال: العدد 167
   */
  title?: string | null;
  publishDate?: string | null;
  cover: number | Media;
  /**
   * يُعرض داخل الصفحة مع زر للتحميل (يُخزَّن في R2).
   */
  pdf: number | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * يُولّد تلقائيًا من العنوان. الرابط الدائم يعتمد على المعرّف الرقمي، فيمكن تعديله بأمان.
   */
  slug?: string | null;
  /**
   * اتركها فارغة لاستخدام العنوان والمقتطف والصورة البارزة افتراضيًا.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads".
 */
export interface Ad {
  id: number;
  /**
   * اسم تعريفي للإدارة فقط، لا يظهر للزوّار.
   */
  title: string;
  /**
   * مكان عرض الإعلان على الموقع.
   */
  placement: 'header' | 'in-article' | 'between-sections' | 'footer';
  format: 'image' | 'script';
  image?: (number | null) | Media;
  /**
   * الرابط الذي يُفتح عند النقر على الإعلان.
   */
  targetUrl?: string | null;
  /**
   * يصف الإعلان لقارئات الشاشة ومحركات البحث.
   */
  alt?: string | null;
  newTab?: boolean | null;
  /**
   * الكود الذي يُحقن في مكان الإعلان نفسه، مثل <ins class="adsbygoogle">…</ins>. محمّل الشبكة الرئيسي (مثل adsbygoogle.js) يُضاف مرة واحدة في إعدادات الموقع.
   */
  bodyScript?: string | null;
  /**
   * كود JS إضافي لرأس الصفحة إذا تطلّبت هذه الوحدة ذلك. اتركه فارغًا في الغالب.
   */
  headScript?: string | null;
  active?: boolean | null;
  /**
   * الأعلى رقمًا يظهر أولًا عند التناوب بين عدّة إعلانات في نفس الموضع.
   */
  priority?: number | null;
  /**
   * اتركه فارغًا للبدء فورًا.
   */
  startDate?: string | null;
  /**
   * اتركه فارغًا بلا تاريخ انتهاء.
   */
  endDate?: string | null;
  /**
   * اعرض الإعلان فقط في صفحات هذه الأقسام. اتركه فارغًا للعرض في كل مكان.
   */
  categories?: (number | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * المسار فقط، يبدأ بشرطة مائلة. مثال: /old-article-123
   */
  from: string;
  /**
   * مسار داخلي (/new) أو رابط كامل.
   */
  to: string;
  type?: ('301' | '302') | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'magazine-issues';
        value: number | MagazineIssue;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'ads';
        value: number | Ad;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredType?: T;
  featuredImage?: T;
  featuredVideoUrl?: T;
  content?: T;
  isRecipe?: T;
  recipe?:
    | T
    | {
        prepTime?: T;
        cookTime?: T;
        servings?: T;
        cuisine?: T;
        ingredients?:
          | T
          | {
              item?: T;
              id?: T;
            };
        instructions?:
          | T
          | {
              step?: T;
              id?: T;
            };
      };
  category?: T;
  tags?: T;
  authors?: T;
  publishedAt?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  legacyWpId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  description?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  videoUrl?: T;
  thumbnail?: T;
  description?: T;
  duration?: T;
  category?: T;
  publishedAt?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazine-issues_select".
 */
export interface MagazineIssuesSelect<T extends boolean = true> {
  issueNumber?: T;
  title?: T;
  publishDate?: T;
  cover?: T;
  pdf?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads_select".
 */
export interface AdsSelect<T extends boolean = true> {
  title?: T;
  placement?: T;
  format?: T;
  image?: T;
  targetUrl?: T;
  alt?: T;
  newTab?: T;
  bodyScript?: T;
  headScript?: T;
  active?: T;
  priority?: T;
  startDate?: T;
  endDate?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  title?: T;
  social?:
    | T
    | {
        facebook?: T;
        x?: T;
        instagram?: T;
        youtube?: T;
        tiktok?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * المقالات المثبّتة في أعلى الصفحة. اتركها فارغة لعرض أحدث المقالات تلقائيًا.
   */
  heroPosts?: (number | Post)[] | null;
  /**
   * القسم الذي يُعرض بتصميم القائمة البارزة (LeadListBlock) أسفل الواجهة. اتركه فارغًا لاستخدام القسم الأول تلقائيًا.
   */
  featuredCategory?: (number | null) | Category;
  videoBand?: {
    enabled?: boolean | null;
    /**
     * اتركها فارغة لعرض أحدث الفيديوهات تلقائيًا.
     */
    pinnedVideos?: (number | Video)[] | null;
  };
  ads?: {
    betweenSections?: boolean | null;
  };
  /**
   * رتّب الأقسام التي تظهر في الصفحة الرئيسية. اتركها فارغة لعرض كل الأقسام.
   */
  sections?:
    | {
        category: number | Category;
        titleOverride?: string | null;
        limit?: number | null;
        /**
         * اتركها فارغة لعرض أحدث المقالات في هذا القسم.
         */
        pinnedPosts?: (number | Post)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu".
 */
export interface MainMenu {
  id: number;
  /**
   * اتركها فارغة لعرض كل الأقسام تلقائيًا.
   */
  items?:
    | {
        label: string;
        /**
         * اربط العنصر بقسم، أو استخدم رابطًا مخصّصًا أدناه.
         */
        category?: (number | null) | Category;
        url?: string | null;
        children?:
          | {
              label: string;
              /**
               * اربط العنصر بقسم، أو استخدم رابطًا مخصّصًا أدناه.
               */
              category?: (number | null) | Category;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  /**
   * تُستخدم عند مشاركة الصفحات التي لا تملك صورة OG خاصة.
   */
  defaultOgImage?: (number | null) | Media;
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'x' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  footerPages?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  newpubLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * يُحقن مرة واحدة داخل <head> في كل الصفحات. مثال: محمّل AdSense، وسم التحقق، GTM (الجزء العلوي).
   */
  headScripts?: string | null;
  /**
   * يُحقن في بداية <body> في كل الصفحات. مثال: وسم GTM (noscript).
   */
  bodyScripts?: string | null;
  /**
   * مثال: G-XXXXXXX لـ Google Analytics 4.
   */
  analyticsId?: string | null;
  /**
   * مفتاح رئيسي لإيقاف كل الإعلانات مؤقتًا دون حذفها.
   */
  adsEnabled?: boolean | null;
  /**
   * يعرض شريط الموافقة ويُفعّل وضع الموافقة من Google. أوقفه لإخفاء الشريط.
   */
  consentEnabled?: boolean | null;
  /**
   * الرابط الذي يفتحه زر «اعرف المزيد». صفحة السياسة نفسها تُنجز في مرحلة لاحقة.
   */
  privacyPolicyUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroPosts?: T;
  featuredCategory?: T;
  videoBand?:
    | T
    | {
        enabled?: T;
        pinnedVideos?: T;
      };
  ads?:
    | T
    | {
        betweenSections?: T;
      };
  sections?:
    | T
    | {
        category?: T;
        titleOverride?: T;
        limit?: T;
        pinnedPosts?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu_select".
 */
export interface MainMenuSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        category?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              category?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  logo?: T;
  defaultOgImage?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerPages?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  newpubLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headScripts?: T;
  bodyScripts?: T;
  analyticsId?: T;
  adsEnabled?: T;
  consentEnabled?: T;
  privacyPolicyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}